# Generated by Django 3.1.2 on 2021-01-12 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 18, 23, 8, 780423)),
        ),
    ]
