# Generated by Django 3.1.2 on 2021-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210112_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='agent_titles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='agent', to='website.Title'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='author_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='author_titles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='author', to='website.Title'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='editor_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='editor_titles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='editor', to='website.Title'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='proofreader_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='proofreader_titles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='proofreader', to='website.Title'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='publisher_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='publisher_titles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publisher', to='website.Title'),
        ),
    ]
