# Generated by Django 3.1.2 on 2021-01-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210112_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
