# Generated by Django 3.1.1 on 2020-10-15 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='following_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following_posts',
            field=models.ManyToManyField(related_name='post_follower', to='network.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_posts',
            field=models.ManyToManyField(related_name='post_owner', to='network.Post'),
        ),
    ]
