# Generated by Django 3.1.2 on 2021-01-20 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connections',
        ),
        migrations.AddField(
            model_name='user',
            name='dr_connections',
            field=models.ManyToManyField(related_name='dr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='ph_connections',
            field=models.ManyToManyField(related_name='ph', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='pt_connections',
            field=models.ManyToManyField(related_name='pt', to=settings.AUTH_USER_MODEL),
        ),
    ]
