# Generated by Django 3.1.5 on 2021-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0004_auto_20210201_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_request',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
