# Generated by Django 3.1.5 on 2021-02-02 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0006_auto_20210201_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_request',
            name='pharmacy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_med_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
