# Generated by Django 3.1.5 on 2021-02-01 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0003_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amount',
        ),
        migrations.AddField(
            model_name='user',
            name='prescriptions',
            field=models.ManyToManyField(related_name='script_owner', to='med_management.Prescription'),
        ),
        migrations.CreateModel(
            name='Med_Request',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='med_management.request')),
                ('amount', models.IntegerField(blank=True, default=None, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_requests', to='med_management.prescription')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_requests', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('med_management.request',),
        ),
    ]
