# Generated by Django 3.1.5 on 2021-02-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0005_med_request_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='count',
            new_name='change',
        ),
        migrations.AddField(
            model_name='entry',
            name='end',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='start',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
